#!/bin/bash 
cp server/nginx.conf /usr/local/nginx/conf/
mkdir /var/www
cp server/index.php /var/www/
cp server/www.conf /etc/php-fpm.d/www.conf 
cp all/nginxd /etc/init.d/
service php-fpm start 
/etc/init.d/nginxd start 
chkconfig php-fpm on 
chkconfig nginxd  on 
