#!/bin/bash
#
# Startup script for the nginx
#
# chkconfig: 345 80 15
# description: Nginx web server.
# Source function library.
. /etc/rc.d/init.d/functions
start(){
    /usr/local/nginx/sbin/nginx
}
stop(){
    kill `cat /usr/local/nginx/logs/nginx.pid`
}
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
esac
exit 0
