#!/bin/sh 
# Unlimit the locked memory and stack size by default

### /ETC/SECURITY/LIMITS.CONF

cat  > /etc/security/limits.conf <<EOF
*               soft    memlock            unlimited
*               hard    memlock            unlimited
*               soft    stack              unlimited
*               hard    stack              unlimited
* hard memlock unlimited
* soft memlock unlimited
EOF
=======
sysctl -w net.ipv4.ip_local_port_range="15000 61000"
sysctl -w net.ipv4.tcp_fin_timeout=30
sysctl -w net.ipv4.tcp_tw_recycle=1
sysctl -w net.ipv4.tcp_tw_reuse=1
sysctl -w net.core.somaxconn=4096
echo "/sbin/ifconfig cni0 txqueuelen 10000" >> /etc/rc.local
echo "/sbin/ifconfig ens2 txqueuelen 10000" >> /etc/rc.local
ifconfig ens2 txqueuelen 10000
ifconfig cni0 txqueuelen 10000
sysctl -w net.core.netdev_max_backlog=8000
sysctl net.ipv4.tcp_max_syn_backlog=8192
